version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: example1234
    volumes:
      - mongo_data:/data/db
      - ./mongodb/import:/import:ro
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: example1234
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass1234
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  backend:
    build: .
    container_name: express_back
    restart: unless-stopped
    environment:
      - EXPRESS_HOST=0.0.0.0
      - PORT=5000
      - MONGO_URI=mongodb://mongo_user:example1234@mongo:27017/?authSource=admin
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:
