version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongodb/import:/import:ro
    ports:
      - "${MONGO_PORT:-27017}:27017"

  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8081" ]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    depends_on:
      - mongo

  backend:
    build: .
    container_name: express_back
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - EXPRESS_HOST=${EXPRESS_HOST}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI_DOCKER}
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:
